
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hmozo/twitter-timeline-config-server.git
          default-label: main
          clone-on-start: true